import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        {
            name: 'GITTE StartStitch 100',
            description: 'Perfect for beginners starting their sewing journey. Features 20 built-in stitches including utility and decorative options, LED work light for clear visibility, and adjustable speed control for learning at your own pace. The free arm design makes it easy to sew cuffs and sleeves.',
            price: 199.99,
            imageUrl: 'https://placehold.co/400x300?text=GITTE+StartStitch+100',
            category: 'Basic',
            brand: 'GITTE',
            stock: 45,
            rating: 4.3,
            features: [
                '20 Built-in Stitches',
                'LED Work Light',
                'Free Arm Design',
                'Adjustable Speed Control',
                'Drop-in Bobbin System',
                '4-Step Buttonhole',
                'Reverse Lever',
                'Built-in Accessory Storage'
            ],
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Singer Simple 3232',
            description: 'A reliable entry-level machine with 32 built-in stitches for versatile sewing projects. Features automatic needle threader to save time and reduce eye strain, convenient drop-in bobbin system for easy loading, and a free arm for circular sewing. Ideal for basic garment construction and home décor projects.',
            price: 179.99,
            imageUrl: 'https://placehold.co/400x300?text=Singer+Simple+3232',
            category: 'Basic',
            brand: 'Singer',
            stock: 38,
            rating: 4.5,
            features: [
                '32 Built-in Stitches',
                'Automatic Needle Threader',
                'Drop-in Bobbin',
                'Free Arm',
                'Built-in LED Light',
                'Adjustable Stitch Length',
                '1-Step Buttonhole',
                'Snap-on Presser Feet'
            ],
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Brother CS6000i',
            description: 'Feature-rich computerized machine offering 60 built-in stitches with LCD display for easy stitch selection. Includes automatic needle threader, wide extension table for quilting projects, and adjustable sewing speed. Perfect for sewers ready to advance beyond basic machines with versatile capabilities for garments, quilts, and home décor.',
            price: 289.99,
            imageUrl: 'https://placehold.co/400x300?text=Brother+CS6000i',
            category: 'Computerized',
            brand: 'Brother',
            stock: 28,
            rating: 4.7,
            features: [
                '60 Built-in Stitches',
                'LCD Display Screen',
                'Automatic Needle Threader',
                'Wide Extension Table',
                'Free Arm',
                'Speed Control Slider',
                '7 Auto-Size Buttonholes',
                'Quick-Set Drop-in Bobbin'
            ],
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'GITTE QuickSew Pro',
            description: 'Mid-range computerized machine with 100 versatile stitches and intuitive LCD screen for precise control. Features automatic thread cutter for efficiency, adjustable speed control, and excellent stitch quality. Ideal for intermediate sewers tackling garment construction, quilting, and decorative projects with professional results.',
            price: 449.99,
            imageUrl: 'https://placehold.co/400x300?text=GITTE+QuickSew+Pro',
            category: 'Computerized',
            brand: 'GITTE',
            stock: 22,
            rating: 4.6,
            features: [
                '100 Built-in Stitches',
                'LCD Display Screen',
                'Automatic Thread Cutter',
                'Speed Control',
                'Needle Up/Down Function',
                'Start/Stop Button',
                '8 One-Step Buttonholes',
                'Adjustable Presser Foot Pressure'
            ],
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Janome DC2200',
            description: 'Advanced computerized machine featuring 200 stitches with memory function for saving custom stitch combinations. Includes adjustable presser foot pressure for different fabric weights, convenient knee lifter for hands-free operation, and superior stitch quality. Perfect for serious sewers creating complex garments, quilts, and artistic projects.',
            price: 549.99,
            imageUrl: 'https://placehold.co/400x300?text=Janome+DC2200',
            category: 'Computerized',
            brand: 'Janome',
            stock: 15,
            rating: 4.8,
            features: [
                '200 Built-in Stitches',
                'Memory Function',
                'Adjustable Presser Foot Pressure',
                'Knee Lifter Included',
                'LCD Display',
                'Automatic Thread Cutter',
                'Superior Plus Feed System',
                'Start/Stop Button'
            ],
            createdAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Singer Heavy Duty 4452',
            description: 'Built with a robust metal frame for sewing heavy fabrics with ease. Delivers impressive 110 stitches per minute for fast project completion, features 32 built-in stitches, and includes heavy-duty accessories. Excellent for denim, canvas, upholstery, and other thick materials requiring strong, consistent stitching power.',
            price: 399.99,
            imageUrl: 'https://placehold.co/400x300?text=Singer+Heavy+Duty+4452',
            category: 'Heavy Duty',
            brand: 'Singer',
            stock: 31,
            rating: 4.7,
            features: [
                'Metal Frame Construction',
                '1100 Stitches Per Minute',
                '32 Built-in Stitches',
                'Heavy-Duty Motor',
                'Stainless Steel Bedplate',
                'Automatic Needle Threader',
                'Drop Feed for Free Motion',
                'Heavy-Duty Accessories Included'
            ],
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'GITTE Industrial 500X',
            description: 'Professional-grade machine with industrial motor for demanding sewing applications. Features 150 built-in stitches, automatic needle threader, and bright LED workspace lighting for precision work. Built for professionals and serious enthusiasts sewing heavy materials, upholstery, leather, and continuous production work with exceptional durability.',
            price: 899.99,
            imageUrl: 'https://placehold.co/400x300?text=GITTE+Industrial+500X',
            category: 'Heavy Duty',
            brand: 'GITTE',
            stock: 12,
            rating: 4.9,
            features: [
                'Industrial Motor',
                '150 Built-in Stitches',
                'Automatic Needle Threader',
                'LED Workspace Lighting',
                'Metal Construction',
                'Adjustable Presser Foot Pressure',
                'High-Speed Stitching',
                'Professional-Grade Accessories'
            ],
            createdAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Brother SE1900',
            description: 'Professional embroidery and sewing combination machine with 5x7 inch embroidery field. Features 240 built-in stitches, USB port for importing designs, and large color LCD touchscreen for easy navigation. Perfect for professional embroiderers and crafters creating custom embroidered garments, gifts, and home décor with precise, beautiful results.',
            price: 1299.99,
            imageUrl: 'https://placehold.co/400x300?text=Brother+SE1900',
            category: 'Embroidery',
            brand: 'Brother',
            stock: 8,
            rating: 5.0,
            features: [
                '5x7 Inch Embroidery Area',
                '240 Built-in Stitches',
                'USB Port',
                'Color LCD Touchscreen',
                '138 Built-in Embroidery Designs',
                'My Custom Stitch Feature',
                'Advanced Needle Threader',
                'Automatic Thread Tension'
            ],
            createdAt: new Date('2024-01-30').toISOString(),
        },
        {
            name: 'GITTE EmbroMaster Elite',
            description: 'Top-of-the-line embroidery machine featuring expansive 8x12 inch embroidery field for large designs. Includes 350 built-in designs, WiFi connectivity for wireless design transfer, and automatic color sorting for efficient multi-color embroidery. Professional choice for custom embroidery businesses, monogramming, and creating stunning embellished garments and accessories.',
            price: 1499.99,
            imageUrl: 'https://placehold.co/400x300?text=GITTE+EmbroMaster+Elite',
            category: 'Embroidery',
            brand: 'GITTE',
            stock: 6,
            rating: 4.9,
            features: [
                '8x12 Inch Embroidery Field',
                '350 Built-in Designs',
                'WiFi Connectivity',
                'Automatic Color Sorting',
                'HD Touchscreen Display',
                'USB and Cloud Import',
                'Advanced Editing Features',
                'Professional Embroidery Hoops'
            ],
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Janome Magnolia 7330',
            description: 'Designed specifically for quilters with extra-wide extension table for large quilt projects. Features 30 essential stitches, adjustable feed dogs for various techniques, and included even feed foot for precise seam matching. Perfect for quilters of all levels creating bed quilts, wall hangings, and intricate patchwork with professional quality.',
            price: 599.99,
            imageUrl: 'https://placehold.co/400x300?text=Janome+Magnolia+7330',
            category: 'Quilting',
            brand: 'Janome',
            stock: 18,
            rating: 4.8,
            features: [
                'Extra-Wide Extension Table',
                '30 Built-in Stitches',
                'Adjustable Feed Dogs',
                'Even Feed Foot Included',
                'Superior Feed System',
                'Automatic Needle Threader',
                'Free Motion Quilting',
                'Precise Stitch Quality'
            ],
            createdAt: new Date('2024-02-12').toISOString(),
        },
        {
            name: 'GITTE QuiltPro 400',
            description: 'Professional quilting machine with generous throat space for maneuvering large quilts. Features 120 built-in stitches, walking foot for even fabric feeding, and automatic height adjustment for thick layers. Ideal for advanced quilters creating intricate designs, free-motion quilting, and handling multiple fabric layers with ease and precision.',
            price: 749.99,
            imageUrl: 'https://placehold.co/400x300?text=GITTE+QuiltPro+400',
            category: 'Quilting',
            brand: 'GITTE',
            stock: 14,
            rating: 4.7,
            features: [
                'Large Throat Space',
                '120 Built-in Stitches',
                'Walking Foot Included',
                'Automatic Height Adjustment',
                'Extension Table',
                'Adjustable Presser Foot Pressure',
                'Free Motion Quilting',
                'Needle Down Function'
            ],
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'Brother PQ1500SL',
            description: 'Specialized straight stitch machine optimized for quilting with impressive 1500 stitches per minute speed. Features straight stitch only for perfect seam quality, included knee lever for hands-free presser foot control, and industrial-style construction. Professional choice for production quilters and sewers requiring consistent, high-speed straight stitching excellence.',
            price: 649.99,
            imageUrl: 'https://placehold.co/400x300?text=Brother+PQ1500SL',
            category: 'Basic',
            brand: 'Brother',
            stock: 10,
            rating: 4.9,
            features: [
                'Straight Stitch Only',
                '1500 Stitches Per Minute',
                'Quilting Optimized',
                'Knee Lever Included',
                'Industrial Construction',
                'Large Work Area',
                'Adjustable Stitch Length',
                'Professional Needle System'
            ],
            createdAt: new Date('2024-02-08').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});